[ADD] 아이템 불러오기
wecode-bootcamp-korea/41-1st-DCB-backend pull request #11
Opened 2023-01-06 06:43 UTC by JongHoB

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
[ADD] 아이템 불러오기

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
[ADD] 아이템 불러오기

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

1. 메인페이지 1번 섹션
![main_page_1](https://user-images.githubusercontent.com/78012131/210945117-da1b881f-2100-4654-8150-6430aaee3171.jpg)

2.메인페이지 2번 섹션
![main_page_2](https://user-images.githubusercontent.com/78012131/210945135-cd3262de-ff5d-4cce-aabf-8440a4e13162.jpg)

3번. 카테고리 페이지 
![상세페이지](https://user-images.githubusercontent.com/78012131/210945183-f7f73446-197a-4d6a-bf2e-d228d22b0e91.jpg)

<br />

## :: 기타 질문 및 특이 사항
orderString 의 Default 값을 "created_at DESC"로 설정했고
String Interpolation으로 인한 
혹시나 모를 SQL INJECTION 때문에 
'WHERE i.category_id=${Number(request.query.page)}'라고 해봤습니다.

2023-01-07 02:01 UTC, Kang-kyunghun requested changes

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/controllers/itemsFetchController.js
> +const itemsFetch = asyncErrorHandler(async (request, response) => {
함수 이름을 동사형으로 잘 만들었네요. 
아래 예시는 일반적으로 쓰이는 예시이니 참고해 주세요.
동사를 가장 앞에쓰고(영문법이랑 비슷하게) 목적어를 사용하는 경우가 일반적이긴 합니다.
```suggestion
const getItemList = asyncErrorHandler(async (request, response) => {
```
or
```suggestion
const getItems = asyncErrorHandler(async (request, response) => {
```

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/models/itemsFetchDao.js
> +    console.log(err);
불필요한 console.log는 제거해 주세요.

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/routes/index.js
> +router.use("/itemsFetch", itemsFetchRouter.router);
itemsFetch 와 items는 하나로 합져 주면 좋을 것 같습니다.
signup, signin은 조금 특수한 경우긴 한데, items 같은 경우 확실하게 어떤 자원을 사용하는지 나타내는 것이 좋을 것 같아요.
- itme detail : ip:port/items/:itemId
- item list : ip:port/items

```suggestion
router.use("/items", itemsRoutes.router);
router.use("/signup", signUpRouter.router);
router.use("/signin", signInRouter.router);
```

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/services/itemsFetchService.js
> +const itemsFetch = async (request) => {
인자로 request를 가져오지 말고 실제로 필요한 값들을 인자로 가져와 주세요.
request를 받아들이고 분석하는 것은 controller에서 끝내 주세요.

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/services/itemsFetchService.js
> +    WHERE i.category_id=${Number(request.query.page)}
category_id가 page라는 key로 들어오나요?? key와 실제 데이터와 매칭이 안 되네요? 확인해 주세요.

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/services/itemsFetchService.js
> +  }
같은 형식의 sql을 반복해서 사용하는데, 이 둘을 한 번 합쳐 보시겠어요?

2023-01-07 02:01 UTC, Kang-kyunghun commented on api/services/itemsFetchService.js
> +  console.log(orderString);
consol.log는 지워주세요.

2023-01-07 05:17 UTC, JongHoB commented on api/services/itemsFetchService.js
> +    WHERE i.category_id=${Number(request.query.page)}
현재 저희 DB에 넣어놓은 카테고리가 
1.캠핑용품 2.조명+랜턴 3.라이프스타일 
인 상황이고
카테고리별 페이지를 보여줄 때 
어제 하신 말씀 중에 
카테고리 이름 그대로 uri에 query string으로 보내줄 수도 있고
번호로 보내서 구분할 수도 있다고 하셔서 
제가 "page"라는 키로 보내게 했는데 (EX. ip:port/itemsFetch/?page=1&sort=(~~))
생각해보니 키 값 이름을 조금 잘못 지은 것 같습니다. 
추가적으로도 보완해서 올려보겠습니다.

2023-01-07 14:50 UTC, JongHoB commented on api/controllers/itemsFetchController.js
> +const itemsFetch = asyncErrorHandler(async (request, response) => {
getItemsList로 변경했습니다!

2023-01-07 14:50 UTC, JongHoB commented on api/routes/index.js
> +router.use("/itemsFetch", itemsFetchRouter.router);
합쳐보았습니다!

2023-01-07 14:56 UTC, JongHoB commented
일단 최대한 query문을 재사용 가능하게 바꿔보았습니다.
그리고 기존의 승님이 올려주신 상세페이지 query문을 
default로 삼고 하게 된 이유는,
메인페이지나 다른 카테고리 페이지에서도 
장바구니를 누르면 
option도 추가되어야하기 때문에 사용했습니다.

query string에서 sort는 그대로 사용했고,
category키를 따로 만들었습니다.
현재 프론트쪽에서 사이트에 만들어놓은 카테고리로는 
'전체보기','캠핑용품','조명+랜턴','라이프스타일'로 되어있기 때문에
'전체보기'=0,
'캠핑용품'=1
'조명+랜턴'=2
'라이프스타일'=3으로 했습니다.

또한 나중을 위해 pageNumber를 추가하여
한 페이지에 최대로 보여지는 데이터의 수를 20으로 정하고 
query string에 page key로 보내게 해봤습니다.

2023-01-08 04:01 UTC, Kang-kyunghun commented
- 구성은 거의다 완성된 것 같습니다.
 - default query도 잘 나눈 것 같습니다.
 - 각 코드의 조립만(위치 조정) 다시 하면 괜찮아 질 것 같습니다.
 - controller에서는 input으로 온 데이터에 대한 분석만 있으면 좋을 것 같습니다. 현재는 cotroller에서 input을 가지고 sql로 사용될 string까지 선택 후 service로 넘기는 그러지 말고 딱 필요한 input값만 service로 넘겨주세요.
 - service에서는 input으로 들어온 데이터 가공 또는 db로부터 받은 data를 가공 위주의 service 로직만 있게 해주세요. query를 만드는 과정은 Dao에서 하는 것이 좋을 것 같습니다.
 - service에 있는 query 만드는 함수들을 따로 파일로 만들어서 관리해도 좋을 것 같습니다.(파일 만드는 것은 옵션입니다.) 그리고 해당 함수들은 dao에서 불러서 query를 최종적으로 만들어보세요.

2023-01-09 00:46 UTC, JongHoB commented
변경해보았습니다.
추후를 위해 검색 기능도 추가시켜서 만들어보았습니다.

2023-01-09 02:24 UTC, Kang-kyunghun commented
고생 하셨습니다.

2023-01-09 02:24 UTC, merged