[ADD]회원가입기능 추가
wecode-bootcamp-korea/41-1st-DCB-backend pull request #6
Opened 2023-01-04 06:44 UTC by JongHoB

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
-회원가입 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
-회원가입 기능 추가

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/78012131/210498611-e6b230fd-7213-4aaa-a019-3f2ce9c56f1e.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/78012131/210498650-3db4a99c-3ed3-47d2-b111-c0b51e72c80d.png">

<br />

## :: 기타 질문 및 특이 사항

2023-01-04 07:24 UTC, Kang-kyunghun commented on routes/index.js
> +router.use("/signUp", signUpRouter.router);
```suggestion
router.use("/signup", signUpRouter.router);
```
보통 URI만들 때 소문자와 dash("-")를 이용해서 많이 만듭니다. 
그런데 signup의 경우 통상적으로 붙여서 만듭니다.

2023-01-04 07:24 UTC, Kang-kyunghun commented on controllers/signUpController.js
> +    console.log(name, email, password, phoneNumber);
불필요한 console.log는 지워주세요.

2023-01-04 07:24 UTC, Kang-kyunghun commented on controllers/signUpController.js
> +  } catch (err) {
에러처리를 middleware에서 할 수 있게 수정해 보시겠어요?

2023-01-04 07:24 UTC, Kang-kyunghun commented on controllers/signUpController.js
> +    console.log(err);
해당 console.log도 꼭 필요하신가요?

2023-01-04 07:24 UTC, Kang-kyunghun commented on models/signUpDao.js
> +    [email]
```suggestion
    SELECT 
      email 
    FROM users 
    WHERE email = ?`,
    [email]
```

2023-01-04 07:24 UTC, Kang-kyunghun commented on models/signUpDao.js
> +    error.statusCode = 500;
status code 500은 백엔드에서 처리하지 못 한 error를 타나냅니다.
400 정도로 수정해 주면 좋을 것 같아요.
```suggestion
    error.statusCode = 400;
```

2023-01-04 07:24 UTC, Kang-kyunghun commented on services/signUpService.js
> +  if (!result) {
```suggestion
  const result = await signUpDao.emailCheck(email);
  
  if (!result) {
```

2023-01-04 07:24 UTC, Kang-kyunghun commented on services/signUpService.js
> +  return signUp;
```suggestion
  }
  
  const saltOrRounds = 12;
  const hashedPassword = await bcrypt.hash(password, saltOrRounds);
  const signUp = await signUpDao.signUp(
    name,
    email,
    hashedPassword,
    phoneNumber
  );
  return signUp;
```

2023-01-04 08:54 UTC, JongHoB commented on routes/index.js
> +router.use("/signUp", signUpRouter.router);
전체적으로 수정해보았습니다.

2023-01-05 00:28 UTC, Kang-kyunghun requested changes

2023-01-05 00:28 UTC, Kang-kyunghun commented on middleware/errorHandling.js
> +};
postman으로 에러도 내보셨나요? 에러처리가 잘 안 됐을 것 같습니다.

error handling 자료 보면 async 함수 처리 방법이 나와 있을거에요!
현재 저희 controller가 async 함수이기 때문에 해당 방법으로 처리해줘야 합니다.

2023-01-05 00:42 UTC, JongHoB commented on middleware/errorHandling.js
> +};
const signUpService = require("../services/signUpService");

 //signUp
 const signUp = async (request, response, next) => {
   try {
     const { name, email, password, phoneNumber } = request.body;
     if (!name || !email || !password || !phoneNumber) {
       let errorMessage = "";
       errorMessage += !name ? "name must be provided! " : "";
       errorMessage += !email ? " email must be provided! " : "";
       errorMessage += !password ? " password must be provided! " : "";
       errorMessage += !phoneNumber ? " phoneNumber must be provided!2 " : "";
       const err = new Error(errorMessage);
       err.statusCode = 400;
       throw err;
     }
     await signUpService.signUp(name, email, password, phoneNumber);
     return response.status(201).json({ message: "userCreated" });
   } catch (err) {
    next(err);
   }
 };
 module.exports = {
   signUp,
 };



controller쪽에 next 를 추가해주면서 
에러핸들링 확인 후 push 했었습니다.

2023-01-05 02:59 UTC, Kang-kyunghun commented
고생 하셨습니다~~!

2023-01-05 02:59 UTC, merged